services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    environment:
      POSTGRES_USER: postgres  # Set a username for postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Set a password for postgres
    networks:
      - net
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data
    restart: unless-stopped

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: my_mongo
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Set a username for MongoDB
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}  # Set a password for MongoDB
    networks:
      - net
    volumes:
      - mongo_data:/data/db  # Persist data
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    container_name: my_chroma
    ports:
      - "8000:8000"  # Expose Chroma on port 8000
    environment:
      CHROMA_DB_TYPE: "sqlite"  # Use SQLite as the database
    networks:
      - net
    volumes:
      - chroma_data:/data  # Map local chroma-data directory to the container's /data
      - ./chroma_config.yaml:/config.yaml  # Map the local config.yaml to the container's config.yaml
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:8.17.3
    container_name: my_elasticsearch
    ports:
      - "9200:9200"  # Expose Elasticsearch on port 9200
    environment:
      ELASTIC_USERNAME: elastic  # Set a username for Elasticsearch
      ELASTIC_PASSWORD: ${DB_PASSWORD}  # Set a password for Elasticsearch
      discovery.type: single-node  # Set the discovery type to single-node
      xpack.security.http.ssl.enabled: false
      xpack.license.self_generated.type: trial
    networks:
      - net
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data  # Persist data
    restart: unless-stopped 

networks:
  net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  chroma_data:
  elasticsearch_data: